Cambios Clopudbuild

diff --git a/cloudbuild-retry.yaml b/cloudbuild-retry.yaml
--- a/cloudbuild-retry.yaml
+++ b/cloudbuild-retry.yaml
@@ -1,34 +1,12 @@
 steps:
-
-- name: gcr.io/cloud-builders/gcloud
-  entrypoint: "bash"
-  args:
-    - "-c"
-    - |
-        max_attempts=5
-        attempt_num=1
-        until curl -i --max-time 10 http://10.10.200.2/TcsNugetServer/nuget || [ $attempt_num -eq $max_attempts ]; do
-          echo "Intento No. $attempt_num fallo! Intentando de nuevo en 5 segundos..."
-          sleep 5
-          attempt_num=$((attempt_num + 1))
-        done
-        if [ $attempt_num -eq $max_attempts ]; then
-          echo "Todos los Intentos han sido erroneos!"
-          exit 1
-        fi
-  id: curl_nuget_10_retry
-options:
-  pool:
-    name: 'projects/came-devops-qa-421116/locations/us-central1/workerPools/m2c-qa-private-pool'
-
-# - name: gcr.io/cloud-builders/docker
+# - name: gcr.io/cloud-builders/gcloud
 #   entrypoint: "bash"
 #   args:
 #     - "-c"
 #     - |
-#         max_attempts=2
+#         max_attempts=5
 #         attempt_num=1
-#         until docker build . -t us-central1-docker.pkg.dev/$PROJECT_ID/m2c-qa-dockerrepostory-servdocument-dev/servdocuments:${SHORT_SHA} -t us-central1-docker.pkg.dev/$PROJECT_ID/m2c-qa-dockerrepostory-servdocument-dev/servdocuments -f Dockerfile || [ $attempt_num -eq $max_attempts ]; do
+#         until curl -i --max-time 10 http://10.10.200.2/TcsNugetServer/nuget || [ $attempt_num -eq $max_attempts ]; do
 #           echo "Intento No. $attempt_num fallo! Intentando de nuevo en 5 segundos..."
 #           sleep 5
 #           attempt_num=$((attempt_num + 1))
@@ -37,21 +15,42 @@ options:
 #           echo "Todos los Intentos han sido erroneos!"
 #           exit 1
 #         fi
-#   id: build_retry
-# - name: 'gcr.io/cloud-builders/docker'
-#   args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/m2c-qa-dockerrepostory-servdocument-dev/servdocuments:${SHORT_SHA}']
-#   id: push
-# - name: gcr.io/google.com/cloudsdktool/cloud-sdk
-#   entrypoint: gcloud
-#   id: deploy
-#   args: 
-#     [
-#       "deploy", "releases", "create", "v-${SHORT_SHA}",
-#       "--delivery-pipeline", "m2c-qa-servdocuments-pipeline",
-#       "--region", "us-central1",
-#       "--annotations", "Repositorio=${REPO_NAME}, commitId=${REVISION_ID}, Rama=${REF_NAME}",
-#       "--images", "servdocuments=us-central1-docker.pkg.dev/$PROJECT_ID/m2c-qa-dockerrepostory-servdocument-dev/servdocuments:${SHORT_SHA}"
-#     ]
+#   id: curl_nuget_10_retry
 # options:
 #   pool:
 #     name: 'projects/came-devops-qa-421116/locations/us-central1/workerPools/m2c-qa-private-pool'
+
+- name: gcr.io/cloud-builders/docker
+  entrypoint: "bash"
+  args:
+    - "-c"
+    - |
+        max_attempts=2
+        attempt_num=1
+        until docker build . -t us-central1-docker.pkg.dev/$PROJECT_ID/m2c-qa-dockerrepostory-servdocument-dev/servdocuments:${SHORT_SHA} -t us-central1-docker.pkg.dev/$PROJECT_ID/m2c-qa-dockerrepostory-servdocument-dev/servdocuments -f Dockerfile || [ $attempt_num -eq $max_attempts ]; do
+          echo "Intento No. $attempt_num fallo! Intentando de nuevo en 5 segundos..."
+          sleep 5
+          attempt_num=$((attempt_num + 1))
+        done
+        if [ $attempt_num -eq $max_attempts ]; then
+          echo "Todos los Intentos han sido erroneos!"
+          exit 1
+        fi
+  id: build_retry
+- name: 'gcr.io/cloud-builders/docker'
+  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/m2c-qa-dockerrepostory-servdocument-dev/servdocuments:${SHORT_SHA}']
+  id: push
+- name: gcr.io/google.com/cloudsdktool/cloud-sdk
+  entrypoint: gcloud
+  id: deploy
+  args: 
+    [
+      "deploy", "releases", "create", "v-${SHORT_SHA}",
+      "--delivery-pipeline", "m2c-qa-servdocuments-pipeline",
+      "--region", "us-central1",
+      "--annotations", "Repositorio=${REPO_NAME}, commitId=${REVISION_ID}, Rama=${REF_NAME}",
+      "--images", "servdocuments=us-central1-docker.pkg.dev/$PROJECT_ID/m2c-qa-dockerrepostory-servdocument-dev/servdocuments:${SHORT_SHA}"
+    ]
+options:
+  pool:
+    name: 'projects/came-devops-qa-421116/locations/us-central1/workerPools/m2c-qa-private-pool'
