test tcpdump

diff --git a/cloudbuild-ip.yaml b/cloudbuild-ip.yaml
--- a/cloudbuild-ip.yaml
+++ b/cloudbuild-ip.yaml
@@ -1,37 +1,26 @@
 steps:
-- name: 'bash'
-  script: |
-    #!/usr/bin/env bash
-    ifconfig
-  id: Show IP
-- name: gcr.io/cloud-builders/gcloud
-  entrypoint: "bash"
-  args:
-    - "-c"
-    - |
-        max_attempts=10
-        attempt_num=1
-        until curl -i --max-time 10 http://10.10.200.2/TcsNugetServer/nuget || [ $attempt_num -eq $max_attempts ]; do
-          echo "Intento No. $attempt_num fallo! Intentando de nuevo en 5 segundos..."
-          sleep 10
-          attempt_num=$((attempt_num + 1))
-        done
-        if [ $attempt_num -eq $max_attempts ]; then
-          echo "Todos los Intentos han sido erroneos!"
-          exit 1
-        fi
-  id: curl_nuget_10_retry
-
-
+# - name: 'bash'
+#   script: |
+#     #!/usr/bin/env bash
+#     ifconfig
+#   id: Show IP
 # - name: gcr.io/cloud-builders/gcloud
 #   entrypoint: "bash"
 #   args:
 #     - "-c"
 #     - |
-#         curl -i http://10.10.200.2/TcsNugetServer/nuget
-#   id: curl_nuget_10
-#   allowFailure: true
-
+#         max_attempts=10
+#         attempt_num=1
+#         until curl -i --max-time 10 http://10.10.200.2/TcsNugetServer/nuget || [ $attempt_num -eq $max_attempts ]; do
+#           echo "Intento No. $attempt_num fallo! Intentando de nuevo en 5 segundos..."
+#           sleep 10
+#           attempt_num=$((attempt_num + 1))
+#         done
+#         if [ $attempt_num -eq $max_attempts ]; then
+#           echo "Todos los Intentos han sido erroneos!"
+#           exit 1
+#         fi
+#   id: curl_nuget_10_retry
 # - name: gcr.io/cloud-builders/gcloud
 #   entrypoint: "bash"
 #   args:
@@ -42,6 +31,13 @@ steps:
 #   id: curl_nuget_198
 #   allowFailure: true
 
+- name: gcr.io/cloud-builders/gcloud
+  entrypoint: "bash"
+  args:
+    - "-c"
+    - |
+        tcpdump -nei any port 80 -s0 -vw issue01.pcap
+  id: test_tcpdump
 options:
   pool:
     name: 'projects/came-devops-qa-421116/locations/us-central1/workerPools/m2c-qa-private-pool'
