try 5 curl

diff --git a/cloudbuild-retry.yaml b/cloudbuild-retry.yaml
--- a/cloudbuild-retry.yaml
+++ b/cloudbuild-retry.yaml
@@ -4,21 +4,72 @@ steps:
   args:
     - "-c"
     - |
-        max_attempts=3
-        attempt_num=1
-        until curl -i http://10.10.200.2/TcsNugetServer/nuget || [ $attempt_num -eq $max_attempts ]; do
-          echo "Intento No. $attempt_num fallo! Intentando de nuevo en 5 segundos..."
-          sleep 5
-          attempt_num=$((attempt_num + 1))
-        done
-        if [ $attempt_num -eq $max_attempts ]; then
-          echo "Todos los Intentos han sido erroneos!"
-          exit 1
-        fi
-  id: curl_nuget_10_retry
-options:
-  pool:
-    name: 'projects/came-devops-qa-421116/locations/us-central1/workerPools/m2c-qa-private-pool'
+        curl -i http://10.10.200.2/TcsNugetServer/nuget
+  id: curl_nuget_10_1
+  allowFailure: true
+
+
+- name: gcr.io/cloud-builders/gcloud
+  entrypoint: "bash"
+  args:
+    - "-c"
+    - |
+        curl -i http://10.10.200.2/TcsNugetServer/nuget
+  id: curl_nuget_10_2
+  allowFailure: true
+
+
+- name: gcr.io/cloud-builders/gcloud
+  entrypoint: "bash"
+  args:
+    - "-c"
+    - |
+        curl -i http://10.10.200.2/TcsNugetServer/nuget
+  id: curl_nuget_10_3
+  allowFailure: true
+
+- name: gcr.io/cloud-builders/gcloud
+  entrypoint: "bash"
+  args:
+    - "-c"
+    - |
+        curl -i http://10.10.200.2/TcsNugetServer/nuget
+  id: curl_nuget_10_4
+  allowFailure: true
+
+
+- name: gcr.io/cloud-builders/gcloud
+  entrypoint: "bash"
+  args:
+    - "-c"
+    - |
+        curl -i http://10.10.200.2/TcsNugetServer/nuget
+  id: curl_nuget_10_5
+  allowFailure: true
+
+
+
+
+# - name: gcr.io/cloud-builders/gcloud
+#   entrypoint: "bash"
+#   args:
+#     - "-c"
+#     - |
+#         max_attempts=3
+#         attempt_num=1
+#         until curl -i http://10.10.200.2/TcsNugetServer/nuget || [ $attempt_num -eq $max_attempts ]; do
+#           echo "Intento No. $attempt_num fallo! Intentando de nuevo en 5 segundos..."
+#           sleep 5
+#           attempt_num=$((attempt_num + 1))
+#         done
+#         if [ $attempt_num -eq $max_attempts ]; then
+#           echo "Todos los Intentos han sido erroneos!"
+#           exit 1
+#         fi
+#   id: curl_nuget_10_retry
+# options:
+#   pool:
+#     name: 'projects/came-devops-qa-421116/locations/us-central1/workerPools/m2c-qa-private-pool'
 
 # - name: gcr.io/cloud-builders/docker
 #   entrypoint: "bash"
