Cambios

diff --git a/cloudbuild-ip.yaml b/cloudbuild-ip.yaml
--- a/cloudbuild-ip.yaml
+++ b/cloudbuild-ip.yaml
@@ -11,7 +11,18 @@ steps:
           sleep 5
           attempt_num=$((attempt_num + 1))
         done
+        if [ $attempt_num -eq $max_attempts ]; then
+          echo "All attempts failed!"
+          exit 1
+        fi
   id: curl_nuget_10_retry
+
+options:
+  pool:
+    name: 'projects/came-devops-qa-421116/locations/us-central1/workerPools/m2c-qa-private-pool'
+
+
+
 
 # - name: gcr.io/cloud-builders/gcloud
 #   entrypoint: "bash"
@@ -20,7 +31,3 @@ steps:
 #     - |
 #         curl --ntlm -u 'TKS\pharevalo:Jiha599*Js*' http://192.168.101.28:8050/Desarrollo/_packaging/DESARROLLO_TEST/nuget/v3/index.json
 #   id: curl_nuget_198
-
-options:
-  pool:
-    name: 'projects/came-devops-qa-421116/locations/us-central1/workerPools/m2c-qa-private-pool'
